In [1]:
import numpy as np

In [2]:
fps15_fps = np.array([15.271185, 11.399590, 11.118002, 10.083773, 8.368452])
fps10_fps = np.array([10.466868, 7.626341, 8.397034, 7.634044, 6.609300])
fps5_fps = np.array([7.86721625, 5.905390, 5.907248, 5.760151, 5.066287])

In [3]:
fps15_fps_ratio = fps15_fps[0] / fps15_fps
fps10_fps_ratio = fps10_fps[0] / fps10_fps
fps5_fps_ratio = fps5_fps[0] / fps5_fps

In [4]:
print(fps15_fps_ratio)
print(fps10_fps_ratio)
print(fps5_fps_ratio)

[1.         1.33962581 1.3735548  1.51443165 1.82485184]
[1.         1.37246263 1.24649585 1.37107777 1.58365757]
[1.         1.33220943 1.33179041 1.36580035 1.55285641]


In [5]:
fps15_base_power = 7.303608
fps10_base_power = 6.104034
fps5_base_power = 5.399202

In [6]:
fps15_power = fps15_base_power * fps15_fps_ratio
fps10_power = fps10_base_power * fps10_fps_ratio
fps5_power = fps5_base_power * fps5_fps_ratio

In [7]:
print(fps15_power)
print(fps10_power)
print(fps5_power)

[ 7.303608    9.78410179 10.03190582 11.06081513 13.32800247]
[6.104034   8.37755854 7.60865303 8.36910531 9.66669967]
[5.399202   7.19286782 7.19060546 7.37423198 8.38418544]


In [8]:
fps15_freq = '1728000 408000000'
fps10_freq = '960000 306000000'
fps5_freq = '115200 306000000'